"""
Enterprise Customer Identity mapping.

The LLM only ever sees / passes around an enterprise_customer_id (ECID).
Each MCP server resolves the ECID to its own internal identifier
(CUST-..., CRM-..., RISK-...) before touching its data source.

This now loads from identity_data.json, generated by
data/generate_bulk_data.py, instead of a hardcoded dict -- so it scales
to however many synthetic customers that script produced (currently ~100).
Re-run that script any time to regenerate a fresh dataset.
"""
from __future__ import annotations

import json
import os

_DATA_PATH = os.path.join(os.path.dirname(__file__), "identity_data.json")

with open(_DATA_PATH) as _f:
    _data = json.load(_f)

NAME_TO_ECID = _data["name_to_ecid"]
ECID_TO_CUST = _data["ecid_to_cust"]
ECID_TO_CRM = _data["ecid_to_crm"]
ECID_TO_RISK = _data["ecid_to_risk"]


def find_ecid_by_name(name: str):
    return NAME_TO_ECID.get(name.strip().lower())
