"""
Core Banking Service -- deployed onto SAP BTP Cloud Foundry.

v2: unlike the original version (hardcoded Python dicts for 4
customers), this loads real CSV data (all ~100 synthetic customers,
generated by data/generate_bulk_data.py) into a real in-memory SQLite
database on startup, and serves it via SQL queries -- same pattern as
sap_ap_service.

API contract is UNCHANGED from v1, so mcp_servers/core_banking/tools.py
in the main app needs no changes:
    GET /health
    GET /accounts/{ecid}      -> {"accounts": [...]}
    GET /transactions/{ecid}  -> {"average_balance":..., "period_days":..., "sample_size":...}
    GET /flags/{ecid}         -> {"active_flags":[...], "active_flag_count":...}
"""
from __future__ import annotations

import csv
import os
import sqlite3

from fastapi import FastAPI, HTTPException

app = FastAPI(title="Core Banking Service (SAP BTP) v2")

HERE = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(HERE, "data")

_db = None


def get_db():
    global _db
    if _db is not None:
        return _db

    con = sqlite3.connect(":memory:", check_same_thread=False)
    con.row_factory = sqlite3.Row
    cur = con.cursor()

    cur.execute("""
        CREATE TABLE accounts (
            ecid TEXT, account_id TEXT, account_type TEXT,
            current_balance REAL, available_balance REAL, status TEXT
        )
    """)
    cur.execute("""
        CREATE TABLE transactions (
            account_id TEXT, transaction_date TEXT, transaction_type TEXT,
            amount REAL, balance_after REAL
        )
    """)
    cur.execute("""
        CREATE TABLE flags (
            ecid TEXT, flag_type TEXT, severity TEXT, status TEXT, description TEXT
        )
    """)

    with open(os.path.join(DATA_DIR, "accounts.csv"), newline="") as f:
        rows = [(r["ecid"], r["account_id"], r["account_type"], float(r["current_balance"]), float(r["available_balance"]), r["status"]) for r in csv.DictReader(f)]
        cur.executemany("INSERT INTO accounts VALUES (?,?,?,?,?,?)", rows)

    with open(os.path.join(DATA_DIR, "transactions.csv"), newline="") as f:
        rows = [(r["account_id"], r["transaction_date"], r["transaction_type"], float(r["amount"]), float(r["balance_after"])) for r in csv.DictReader(f)]
        cur.executemany("INSERT INTO transactions VALUES (?,?,?,?,?)", rows)

    with open(os.path.join(DATA_DIR, "flags.csv"), newline="") as f:
        rows = [(r["ecid"], r["flag_type"], r["severity"], r["status"], r["description"]) for r in csv.DictReader(f)]
        cur.executemany("INSERT INTO flags VALUES (?,?,?,?,?)", rows)

    con.commit()
    _db = con
    return _db


@app.get("/health")
def health():
    db = get_db()
    counts = {
        "accounts": db.execute("SELECT COUNT(*) FROM accounts").fetchone()[0],
        "transactions": db.execute("SELECT COUNT(*) FROM transactions").fetchone()[0],
        "flags": db.execute("SELECT COUNT(*) FROM flags").fetchone()[0],
    }
    return {"status": "ok", "source": "SAP_BTP", "row_counts": counts}


@app.get("/accounts/{ecid}")
def accounts(ecid: str):
    db = get_db()
    rows = db.execute("SELECT account_id, account_type, current_balance, available_balance, status FROM accounts WHERE ecid = ?", (ecid,)).fetchall()
    if not rows:
        raise HTTPException(status_code=404, detail="CUSTOMER_NOT_FOUND")
    return {"accounts": [dict(r) for r in rows]}


@app.get("/transactions/{ecid}")
def transactions(ecid: str, days: int = 90):
    db = get_db()
    account_ids = [r[0] for r in db.execute("SELECT account_id FROM accounts WHERE ecid = ? AND account_type='SAVINGS'", (ecid,)).fetchall()]
    if not account_ids:
        raise HTTPException(status_code=404, detail="CUSTOMER_NOT_FOUND")

    placeholders = ",".join("?" for _ in account_ids)
    rows = db.execute(f"SELECT balance_after FROM transactions WHERE account_id IN ({placeholders})", account_ids).fetchall()
    balances = [r[0] for r in rows]
    avg_balance = round(sum(balances) / len(balances), 2) if balances else 0.0

    return {"average_balance": avg_balance, "period_days": days, "sample_size": len(balances)}


@app.get("/flags/{ecid}")
def flags(ecid: str):
    db = get_db()
    # confirm the customer exists at all (via accounts table) before answering "no flags"
    exists = db.execute("SELECT 1 FROM accounts WHERE ecid = ? LIMIT 1", (ecid,)).fetchone()
    if not exists:
        raise HTTPException(status_code=404, detail="CUSTOMER_NOT_FOUND")

    rows = db.execute("SELECT flag_type, severity, status, description FROM flags WHERE ecid = ? AND status='ACTIVE'", (ecid,)).fetchall()
    active_flags = [dict(r) for r in rows]
    return {"active_flags": active_flags, "active_flag_count": len(active_flags)}


if __name__ == "__main__":
    import uvicorn

    port = int(os.environ.get("PORT", 8080))
    uvicorn.run(app, host="0.0.0.0", port=port)
